version: "1.0"
stages:
  - "clone"
  - "build"
  - "deploy"
steps:
  main_clone:
    type: "git-clone"
    title: "Clone main repository..."
    repo: "codefresh-contrib/nomad-sample-app"
    revision: "${{CF_BRANCH}}"
    stage: "clone"
  build:
    title: "Building Docker Image"
    type: "build"
    image_name: "nomad-sample-app"
    tag: "${{CF_BRANCH_TAG_NORMALIZED}}"
    dockerfile: "Dockerfile"
    stage: "build"
  prepareJob:
    title: "Preparing Nomad job"
    image: bhgedigital/envsubst
    stage: deploy
    commands:
      - envsubst < docker-job.hcl > docker-job-export.hcl
      - cat docker-job-export.hcl
  runJob:
    title: "Deploying Nomad job"
    image: djenriquez/nomad
    stage: deploy
    commands:
      - nomad run docker-job-export.hcl  
